### ISSUE TITLE
pyenv: version `system' not installed

### ISSUE THREAD

**Issue by programes** [yyuu/pyenv#622]
```
➜  ~ pyenv rehash  
➜  ~ pyenv global system
pyenv: version `system' not installed
➜  ~ pyenv local system 
pyenv: version `system' not installed
➜  ~ pyenv versions    
  system
* 3.5.1 (set by /home/mega/.python-version)
➜  ~ 
```

**Comment by yyuu** [comment]
I couldn't reproduce the problem. It's working for me as it should be. If the problem persists for you, please post some Dockerfile to reproduce the issue then I'll try digging.

**Comment by djl** [comment]
This has suddenly started happening to me out of the blue:

```
$ pyenv versions     
* system (set by /home/djl/.pyenv/version)
$ pyenv global system
pyenv: version `system' not installed
$ pyenv virtualenv foo
pyenv-virtualenv: `system' is not installed in pyenv.
```

I narrowed it down to [this line](https://github.com/pyenv/pyenv/blob/master/libexec/pyenv-prefix#L34). That code assumes that the Python executable resides in a `bin` directory. On systems where `*/sbin` and is a symlink to `*/bin` (and `sbin` is first in the `$PATH`) this breaks. Arch Linux is an example of this:

```
$ which python
/usr/sbin/python
$ ls -ld /usr/sbin/
lrwxrwxrwx 1 root root 3 Dec  6 14:19 /usr/sbin -> bin
```

This probably could be considered a bug in users' config and doesn't warrant a fix in pyenv itself. It would be nice to not assume that everything resides in a ` */bin` directory, though.

Just thought I'd post this in case anyone else stumbles upon the same issue :smiley:

**Comment by tommyjcarpenter** [comment]
I just hit this issue in Arch Linux (fresh install of Arch). What is the recommended remedy?

**Comment by djl** [comment]
My solution was to just remove the symlinked `*/sbin` paths from my `$PATH`.

**Comment by tommyjcarpenter** [comment]
This is on a fresh install of Arch and the pyenv package, and it requires me to alter my path? I do not agree that this isn't a pyenv bug then.

**Comment by tommyjcarpenter** [comment]
@yyuu I would like to reopen this issue. Simply use `archlinux/base`, install yay, and then install pyenv, and this issue will happen.

**Comment by djl** [comment]
FWIW I didn't have to alter my *default* `$PATH`. My untouched `/etc/profile` doesn't include any `sbin` directories and I'm not aware of any OS or distro that does include these directories for non-`root` users by default.

But it would be nice to get this fixed in pyenv. I agree that it is a bad assumption that a binary will always reside in `[...]/bin/`.

**Comment by niccolomineo** [comment]
I was dealing with this today in Ubuntu.

After some trial and error, a message appeared urging to install the `python3-venv` package, which solved the issue for me.

**Comment by niccolomineo** [comment]
I was still hitting this today in Ubuntu.

After some trial and error, a message appeared urging to install the python3-venv package, which solved the issue for me.

**Comment by jonashaag** [comment]
Still a problem; I had a symlink somewhere in `~/.local/bin` to `/usr/bin/pythonX` and it failed. Had to remove that symlink and change my `PATH`.

**Comment by guilhermelowa** [comment]
Having same issue with Ubuntu 20.04. 

`
$ pyenv versions
Warning: no Python detected on the system
$ pyenv global system
pyenv: system version not found in PATH
$ which python

$ which python 3
/usr/bin/python3
$ echo $PYTHON_PATH

`

I have two aliases at my .bashrc:
alias python=python3
alias pip=pip3

I do have python3-venv package, as cited above as a possible solution, and all the [Prerequisites packages](https://github.com/pyenv/pyenv/wiki/Common-build-problems)

Also, I can install a version without any problems with `pyenv install <version>`.

**Comment by PrasannaVenkadesh** [comment]
> Having same issue with Ubuntu 20.04.

@guilhermelowa Ubuntu 20.04 comes with both 2.7 and 3.8 versions. It doesn't assume one particular version to be default, instead one have to be explicit about what version of python they want to invoke. `python3` and `python2` and by default `python` doesn't point to any `python2` or `python3` also setting alias doesn't work since `pyenv` seems to look for `python` $PATH locations.

Hence, the solution that worked for me is to create a symbolic link to `python3` or `python2` whichever you want.

    sudo ln -s /usr/bin/python3 /usr/bin/python

Now `which python` points to `/usr/bin/python` and `pyenv` happily uses it.

**Comment by cshintov** [comment]
Thank @PrasannaVenkadesh. Solved my problem! :+1:

**Comment by srsakhamuri** [comment]
On Ubuntu 20.04 fixed by running `sudo apt-get install python-is-python3` I believe it does similar thing as @PrasannaVenkadesh suggested.

**Comment by huyz** [comment]
I solved my problem by manually editing `~/.pyenv/version` back to `system`

**Comment by heeeeeeeeeeh** [comment]
I solved mine by adding $PYENV_ROOT/libexec to my path

**Comment by native-api** [comment]
> I solved mine by adding $PYENV_ROOT/libexec to my path

Not sure what exactly you fixed by that, but that's a terrible solution for anything. Subcommands will likely malfunction is invoked directly rather than through the `pyenv` launcher because the latter sets some necessary envvars.

**Comment by native-api** [comment]
Since [#1655](https://github.com/pyenv/pyenv/pull/1655), `system` is considered installed if `python`, `python3` or `python2` is on PATH after `$(pyenv-root)/shims`.

So if this happens, most likely, you do not have any system-provided Python installed.
